version: '3.8'
services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: "expensesdb"
      POSTGRES_USER: "expensesuser"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - expenses-tracking
  web:
    container_name: web
    build: .
    command: ./entrypoint.sh
    ports:
      - "8001:8000"
    platform: linux/amd64
    environment:
      DEBUG: True
      SECRET_KEY: "your-django-secret-key"
      POSTGRES_DB: "expensesdb"
      POSTGRES_USER: "expensesuser"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      DJANGO_SUPERUSER_PASSWORD: "testpassword"
      DJANGO_SUPERUSER_EMAIL: "example@example.com"
      DJANGO_SUPERUSER_USERNAME: "admin"
    depends_on:
      - db
    networks:
      - expenses-tracking

networks:
  expenses-tracking:
    external: false

volumes:
  postgres_data: